version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - NODE_ENV=development
    env_file:
      - .env

  database:
    image: postgres:15.1
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  pg-data:
